# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gem',
            old_name='name',
            new_name='title',
        ),
    ]
