# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 18:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0002_auto_20160217_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gems', to=settings.AUTH_USER_MODEL),
        ),
    ]
