# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid
import woodshop.gems.models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0003_auto_20160217_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=woodshop.gems.models.image_dir_path)),
                ('gem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='gems.Gem')),
            ],
        ),
    ]
