# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import woodshop.gems.models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0004_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(max_length=255, upload_to=woodshop.gems.models.image_dir_path),
        ),
    ]
