# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='t_id',
            new_name='id',
        ),
    ]
