# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 20:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import woodshop.api.gems.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default='', max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=128)),
                ('is_leaf', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gems', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='gems', to='gems.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=255, upload_to=woodshop.api.gems.models.image_dir_path)),
                ('gem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='gems.Gem')),
            ],
        ),
        migrations.AddField(
            model_name='gem',
            name='main_picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gem_asset', to='gems.Picture'),
        ),
    ]
