# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gem',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
