# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0002_gem_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gem',
            old_name='author',
            new_name='vendor',
        ),
    ]
