# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0002_auto_20160219_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='gem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='gems.Category'),
        ),
    ]
