# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0003_auto_20160223_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
