# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0004_auto_20160223_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='gems', to='gems.Category'),
        ),
    ]
