# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gems', '0005_auto_20160229_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gem',
            name='main_picture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gem_asset', to='gems.Picture'),
        ),
    ]
