# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20160226_0251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': (('add_review', 'Add Review'),)},
        ),
    ]
