# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20160229_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': (('can_add_review', 'Add Review'),)},
        ),
    ]
